# serverless.yml
service: bts-identifier

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.source}/*"

functions:
  process:
    handler: functions/identify/handler.process
    environment:
      SOURCE: ${self:custom.source}
      TARGET: ${self:custom.target}

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - venv/**

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    slim: true
    strip: false
  source:
    bts-identifier-source
  target:
    bts-identifier-target
    